CREATE TABLE companies (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  acronym VARCHAR(3) NOT NULL UNIQUE
);

CREATE TABLE aiports (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  acronym VARCHAR(3) NOT NULL UNIQUE
)

CREATE TABLE flights (
  id SERIAL PRIMARY KEY,
  "companyId" INTEGER NOT NULL REFERENCES "companies"("id"),
  acronym VARCHAR(7) NOT NULL UNIQUE,
  "originId" INTEGER NOT NULL REFERENCES "aiports"("id"),
  "destinationId" INTEGER NOT NULL REFERENCES "aiports"("id"),
  "takeOff" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
  arrival TIMESTAMP WITHOUT TIME ZONE DEFAULT NULL
);